export const SET_USER_PROFILE = 'SET_USER_PROFILE' ;
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_BLOG_POSTS = 'SET_BLOG_POSTS' ;
export const SET_LIBRARY_BOOKS = 'SET_LIBRARY_BOOKS' ;
export const SET_EVENTS = 'SET_EVENTS' ;
export const SET_MENTORS = 'SET_MENTORS' ;
export const SET_PROJECTS = 'SET_PROJECTS' ;
export const SET_COURSES = 'SET_COURSES' ;
export const SET_PROGRESS = 'SET_PROGRESS';