export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_BLOG_POSTS = 'SET_BLOG_POSTS' ;
export const SET_LIBRARY_BOOKS = 'SET_LIBRARY_BOOKS' ;