export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const SET_BLOG_POSTS = 'SET_BLOG_POSTS';

export const SET_LIBRARY_BOOKS = 'SET_LIBRARY_BOOKS';
export const ADD_LIBRARY_BOOK = 'ADD_LIBRARY_BOOK';
export const EDIT_LIBRARY_BOOK = 'EDIT_LIBRARY_BOOK';
export const DELETE_LIBRARY_BOOK = 'DELETE_LIBRARY_BOOK';

export const SET_EVENTS = 'SET_EVENTS';
export const ADD_EVENT = 'ADD_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';

export const SET_MENTORS = 'SET_MENTORS';
export const ADD_MENTOR = 'ADD_MENTOR';
export const EDIT_MENTOR = 'EDIT_MENTOR';
export const DELETE_MENTOR = 'DELETE_MENTOR';

export const SET_PROJECTS = 'SET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const SET_COURSES = 'SET_COURSES';
export const ADD_COURSE = 'ADD_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const SAVE_COURSE_VIDEOS = 'SAVE_COURSE_VIDEOS';
export const DELETE_COURSE = 'DELETE_COURSE';

export const SET_PROGRESS = 'SET_PROGRESS';
